### ISSUE TITLE
the output of the AutoEncoder last layer should not pass sigmoid?

### ISSUE THREAD

**Issue by JackerGao** [zc8340311/RobustAutoencoder#10]
In script DeepAE.py, i think the last layer of the AE should not pass sigmoid.  can you give me your suggestions in your time, thx.

**Comment by zc8340311** [comment]
Hi Jacker,
Thanks a lot for your interests on my paper.

Since my input data, digit pictures are from 0-1, so the last sigmoid also regularize output to 0-1.

Thanks

Sincerely,
Chong

**Comment by zc8340311** [comment]
But it is not deterministic. I found relu is a good choice too. 
You can change the autoencoder part on your demand.  As you can see, the Robust Autoencoder is framework, The autoencoder part can be changed to anything that sharing similar "dimension reduction and reconstruction" ideas.

**Comment by JackerGao** [comment]
> Hi Jacker,
> Thanks a lot for your interests on my paper.
> 
> Since my input data, digit pictures are from 0-1, so the last sigmoid also regularize output to 0-1.
> 
> Thanks
> 
> Sincerely,
> Chong
Hi, Chong,
Thanks for your reply, let  me know the reason about it. i often use AE on the structurized data and the last layer don`t pass sigmoid, so i think it dont need to pass sigmoid here. i make a mistake. thx for your answer.
