### ISSUE TITLE
Share the slides you presented at KDD 2017?

### ISSUE THREAD

**Issue by jmren168** [zc8340311/RobustAutoencoder#3]
Hi, 

Is it possible to share the slides you presented at KDD 2017? 
If so, I would be highly appreciated.
Thanks in advance. 

JM

**Comment by zc8340311** [comment]
Hi,
No problem. Uploaded to the folder "slides".

Chong

**Comment by jmren168** [comment]
Get it and many thanks :)

Best,
JM
