### ISSUE TITLE
loss calculation at epoch end only over last batch (DAE) 

### ISSUE THREAD

**Issue by robroe-tsi** [zc8340311/RobustAutoencoder#6]
Hi,

I have one question regarding the calculation of the loss at the end of each epoch in the DAE script (RobustAutoencoder/experiments/Outlier Detection/DAE_tensorflow.py).

Currently the code look like:
```Python
# ....
        error = []
        sample_size = X.shape[0]
        turns = sample_size / batch_size

        for i in xrange(iteration):
            for turn in xrange(turns):

                start = (batch_size*turn) % sample_size
                end = (batch_size*(turn+1)) % sample_size

                sess.run(train_step,feed_dict = {input_x:X[start:end]})
            e = cost.eval(session = sess,feed_dict = {input_x: X[start:end]})
            if verbose and i%20==0:
                print "    iteration : ", i ,", cost : ", e
            error.append(e)
# ....
```
As the variable "start" and "end" still point to last used batch in the epoch the loss value will always be calculated only over the records of the last batch.
Wouldn't it make more sense to calculate it using the full dataset X - like
```Python
# ....
        error = []
        sample_size = X.shape[0]
        turns = sample_size / batch_size

        for i in xrange(iteration):
            for turn in xrange(turns):

                start = (batch_size*turn) % sample_size
                end = (batch_size*(turn+1)) % sample_size

                sess.run(train_step,feed_dict = {input_x:X[start:end]})
            e = cost.eval(session = sess,feed_dict = {input_x: X})
# ....
```
?

Best, Roberto

BTW: extremely interesting paper - thanks for making the code available

**Comment by zc8340311** [comment]
Hi Roberto,
Thanks for your interests on my paper.
I think your comments are reasonable. I did not think much here. I will make changes on it.
